// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5dQ2DlO-V1V3xF3-7pvhDIk6xi1I4a5c',
    appId: '1:382221574224:web:db95ad26a25981471bb155',
    messagingSenderId: '382221574224',
    projectId: 'tenis-gs',
    authDomain: 'tenis-gs.firebaseapp.com',
    storageBucket: 'tenis-gs.firebasestorage.app',
    measurementId: 'G-K8DBB029Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCdphhLaVVEVvM4s2HQ0dyxAqTlVrqYx4',
    appId: '1:382221574224:android:128cb2fee8518ed61bb155',
    messagingSenderId: '382221574224',
    projectId: 'tenis-gs',
    storageBucket: 'tenis-gs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFDA14dZcinnHaHLSoZ9bLws9jJn9L4QI',
    appId: '1:382221574224:ios:1ff4c82a619a37991bb155',
    messagingSenderId: '382221574224',
    projectId: 'tenis-gs',
    storageBucket: 'tenis-gs.firebasestorage.app',
    iosBundleId: 'com.example.aaaaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFDA14dZcinnHaHLSoZ9bLws9jJn9L4QI',
    appId: '1:382221574224:ios:1ff4c82a619a37991bb155',
    messagingSenderId: '382221574224',
    projectId: 'tenis-gs',
    storageBucket: 'tenis-gs.firebasestorage.app',
    iosBundleId: 'com.example.aaaaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5dQ2DlO-V1V3xF3-7pvhDIk6xi1I4a5c',
    appId: '1:382221574224:web:e9312585cafaf0591bb155',
    messagingSenderId: '382221574224',
    projectId: 'tenis-gs',
    authDomain: 'tenis-gs.firebaseapp.com',
    storageBucket: 'tenis-gs.firebasestorage.app',
    measurementId: 'G-ME5HFH9GEP',
  );
}
